CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE TEACHER(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)NOT NULL,
    email VARCHAR(150)NOT NULL UNIQUE,
    position VARCHAR(100)NOT NULL
    phone VARCHAR(20)NOT NULL,
    img VARCHAR(255)NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);